In [1]:
from tensorflow.contrib import learn
import numpy as np

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
max_document_length = 10
vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length)

Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.


In [3]:
corpus = [
    'My name is XYZ',
    'I live in Bangalore',
    'A Picture tells thousands of words',
    'Bangalore traffic is getting terrible day by day.'
]

In [4]:
list(vocab_processor.fit_transform(corpus))

Instructions for updating:
Please use tensorflow/transform or tf.data.


[array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0]),
 array([5, 6, 7, 8, 0, 0, 0, 0, 0, 0]),
 array([ 9, 10, 11, 12, 13, 14,  0,  0,  0,  0]),
 array([ 8, 15,  3, 16, 17, 18, 19, 18,  0,  0])]

In [5]:
vocab_processor.vocabulary_._mapping

{'<UNK>': 0,
 'A': 9,
 'Bangalore': 8,
 'I': 5,
 'My': 1,
 'Picture': 10,
 'XYZ': 4,
 'by': 19,
 'day': 18,
 'getting': 16,
 'in': 7,
 'is': 3,
 'live': 6,
 'name': 2,
 'of': 13,
 'tells': 11,
 'terrible': 17,
 'thousands': 12,
 'traffic': 15,
 'words': 14}